[transforms.dedupe]
title = "Dedupe events"
allow_you_to_description = "Prevent duplicate Events from being outputted"
beta = false
common = false
function_category = "filter"
input_types = ["log"]
output_types = ["log"]

<%= render("_partials/_component_options.toml", type: "transform", name: "dedupe") %>

[transforms.dedupe.options.fields]
type = "table"
description = "Options controlling what fields to match against"

[transforms.dedupe.options.fields.match]
type = "[string]"
common = true
examples = [["field1", "field2"]]
default = ["timestamp"]
description = "The field names consider when deciding if an Event is a duplicate."

[transforms.dedupe.options.cache]
type = "table"
description = "Options controlling how we cache recent Events for future duplicate checking."

[transforms.dedupe.options.cache.num_entries]
type = "int"
common = true
examples = [5000]
default = 5000
description = "The number of recent Events to cache and compare new incoming Events against."
